### ISSUE TITLE
Create users table and random users

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/mapr-music#73]
To be able to work with a proper recommendation engines ( see issue #61 ) we need to have user.

* [x] Create simple table user with: userid, firstname, lastname
* [x] Generate sample users for this table
* [x] Associate the "web user" to this table (in wf and table)
   * [x] jdoe/music  (John Doe)  
   * [x] sdavis/music (Simone Davis)
   * [x] mdupont/music (Mike Dupont)

* Then explain how to run the ML on this data (we should have a dataset by default ad explain how to run it)

**Comment by mmamadilov** [comment]
Changes can be found at [feature/Recommendation_engine](https://github.com/mapr-demos/mapr-music/blob/feature/Recommendation_engine) branch. Refer the [documentation](https://github.com/mapr-demos/mapr-music/blob/feature/Recommendation_engine/doc/deployment-order.md) in order to deploy and test the app.
